export const data = {
    products: [
      {
        name: 'Waist Beads',
        slug: 'waist-beads',
        category: 'Accessories',
        image: '/Images/waistbead1.png',
        price: 14.99,
        brand: 'JariAfrica',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'Beautiful handmade waist beads from Ghana.',
      },
      {
        name: 'Necklace',
        slug: 'necklace',
        category: 'Accessories',
        image: '/Images/neckpiece1.png',
        price: 24.99,
        brand: 'JariAfrica',
        rating: 4.0,
        numReviews: 8,
        countInStock: 15,
        description: 'Elegant necklace made with beads from Nigeria.',
      },
      {
        name: 'Hand Bangles',
        slug: 'hand-bangles',
        category: 'Accessories',
        image: 'Images/Amer_bangle.png',
        price: 19.99,
        brand: 'JariAfrica',
        rating: 4.2,
        numReviews: 12,
        countInStock: 10,
        description: 'Stylish hand bangles handmade in Kenya.',
      },
      {
        name: 'Anklet',
        slug: 'anklet',
        category: 'Accessories',
        image: '/Images/anklet_1.jpeg',
        price: 9.99,
        brand: 'JariAfrica',
        rating: 3.8,
        numReviews: 5,
        countInStock: 8,
        description: 'Beautiful anklet made with beads from Ghana.',
      },
      {
        name: 'Woven Hand Bag',
        slug: 'woven-hand-bag',
        category: 'Bags',
        image: 'Images/black and white.png',
        price: 29.99,
        brand: 'JariAfrica',
        rating: 4.7,
        numReviews: 15,
        countInStock: 5,
        description: 'Stylish and durable hand woven bag from Tanzania.',
      },
    ],
  };
  
  // export default data;
  